source: 'templates'
destination: 'build'

# Exclude files from copy across to patrickbower.com repo
# exclude: ['*.map']

# Do not erase (clean), before adding jekyll rebuilds
keep_files: [ 'images', 'scripts', 'styles', 'fonts', 'CNAME' ]
